/**
 * Custom Worker Entry Point for xConvert24.com
 *
 * This file documents the Worker's exported interface. The actual deployed entry
 * is generated by `scripts/build-worker-entry.mjs` which merges:
 *   1. Astro's generated fetch handler (from `astro build`)
 *   2. The email handler (from `src/email-handler.ts`)
 *
 * Cloudflare Workers require a default export with handler methods.
 * This Worker exports:
 *   - fetch(): Handles all HTTP requests (Astro SSR pages + API routes)
 *   - email(): Handles inbound emails via Cloudflare Email Routing
 *
 * Build pipeline:
 *   1. `astro build` → generates dist/server/entry.mjs (fetch only)
 *   2. `node scripts/build-worker-entry.mjs` → adds email() to entry.mjs
 *   3. `wrangler deploy` → deploys the combined Worker
 *
 * @see src/email-handler.ts for the email handler implementation
 * @see scripts/build-worker-entry.mjs for the build integration
 */

import { emailHandler } from './src/email-handler';
import type { EmailMessage, Env } from './src/email-handler';

export default {
  /**
   * HTTP request handler — delegates to Astro's SSR runtime.
   * Handles all pages, API endpoints, and static assets.
   * Populated at build time from Astro's generated Worker entry.
   */
  async fetch(request: Request, env: Env, ctx: ExecutionContext): Promise<Response> {
    // This is a type-reference file. The actual fetch handler is Astro's generated one.
    // See dist/server/entry.mjs after running `npm run build`.
    throw new Error('Do not run _worker.ts directly. Use `npm run build` then `wrangler deploy`.');
  },

  /**
   * Inbound email handler — Cloudflare Email Routing.
   *
   * Receives emails sent to contact@, support@, info@xconvert24.com
   * and forwards them to the address in SWF_NOTIFY_EMAIL secret.
   *
   * Guarantees:
   * - Never throws an unhandled exception
   * - Logs errors for missing config or forward failures
   * - Discards messages gracefully when destination is not configured
   */
  async email(message: EmailMessage, env: Env, ctx: ExecutionContext): Promise<void> {
    return emailHandler(message, env, ctx);
  },
} satisfies ExportedHandler<Env>;
