-- Batch insert 200 new blog ideas into BlogsInPipeline (starting after existing 120)
-- Category: Conversion & Measurement (1-40)
INSERT INTO BlogsInPipeline (BlogName) VALUES
('Why the World Uses Different Measurement Systems'),
('Metric vs Imperial Explained'),
('How to Convert Miles to Kilometres Mentally'),
('Why the US Still Uses Imperial Units'),
('History of the Metric System'),
('Understanding Area Measurements'),
('Acres vs Hectares'),
('Feet vs Metres'),
('Why Nautical Miles Exist'),
('How GPS Uses Coordinates'),
('Common Construction Conversions'),
('Land Measurement Guide'),
('Unit Conversion Mistakes'),
('Engineering Conversion Cheat Sheet'),
('Most Popular Conversion Tools'),
('Scientific Notation Explained'),
('Everyday Conversion Examples'),
('Quick Weight Conversion Tricks'),
('Distance Conversion Guide'),
('Temperature Conversion Guide'),
('Understanding Volume Measurements'),
('Cooking Measurement Conversions'),
('Baking Conversion Guide'),
('Converting Recipes Internationally'),
('Metric System for Beginners'),
('Educational Conversion Tools'),
('Physics Unit Guide'),
('SI Units Explained'),
('Why Standards Matter'),
('International Measurement Standards'),
('Travel Conversion Guide'),
('Aviation Measurement Units'),
('Maritime Measurement Systems'),
('Weather Unit Conversions'),
('Understanding Altitude Units'),
('Mapping and Scale Conversion'),
('Surveying Measurements'),
('Industrial Conversion Guide'),
('Healthcare Measurement Standards'),
('Laboratory Measurement Conversions');

-- Category: Finance & Money (41-80)
INSERT INTO BlogsInPipeline (BlogName) VALUES
('How Compound Interest Creates Wealth'),
('The Rule of 72 Explained'),
('Best Savings Strategies'),
('Inflation Explained'),
('Understanding APR'),
('Mortgage Basics'),
('Fixed vs Variable Rates'),
('Retirement Planning Guide'),
('How Much Should You Save?'),
('Net Worth Tracking'),
('Budgeting Methods Compared'),
('Emergency Fund Guide'),
('Debt Snowball Method'),
('Debt Avalanche Method'),
('Dividend Investing Basics'),
('Passive Income Strategies'),
('FIRE Movement Explained'),
('Pension Planning UK'),
('Financial Independence Calculator Guide'),
('Common Investing Mistakes'),
('Time Value of Money'),
('Index Funds Explained'),
('ETF Investing Basics'),
('Tax Efficient Investing'),
('Wealth Building Habits'),
('Saving vs Investing'),
('High Yield Savings Accounts'),
('Understanding Bonds'),
('Understanding Risk'),
('Financial Goal Setting'),
('Compound Interest Examples'),
('Long-Term Investing Case Studies'),
('Understanding Asset Allocation'),
('Investment Diversification'),
('Inflation-Proof Assets'),
('Financial Ratios Explained'),
('Budgeting Apps Compared'),
('Side Hustle Income Planning'),
('Cost of Living Calculations'),
('Personal Finance Checklist');

-- Category: Crypto (81-120)
INSERT INTO BlogsInPipeline (BlogName) VALUES
('What Is Bitcoin?'),
('What Are Satoshis?'),
('Bitcoin Halving Explained'),
('Understanding Bitcoin Supply'),
('Bitcoin vs Gold'),
('Bitcoin DCA Strategy'),
('Bitcoin Volatility Explained'),
('Self-Custody Guide'),
('Hardware Wallet Basics'),
('Crypto Security Tips'),
('Understanding Stablecoins'),
('What Is Ethereum?'),
('What Is Solana?'),
('What Is DeFi?'),
('Crypto Tax Basics UK'),
('Bull vs Bear Markets'),
('Market Cap Explained'),
('Tokenomics Guide'),
('Understanding Liquidity'),
('Staking Explained'),
('Yield Farming Basics'),
('Crypto Portfolio Management'),
('Position Sizing Guide'),
('Risk Management for Traders'),
('Common Crypto Scams'),
('Rug Pull Warning Signs'),
('How Exchanges Work'),
('Centralized vs Decentralized Exchanges'),
('Understanding Gas Fees'),
('Blockchain Basics'),
('Bitcoin Mining Explained'),
('Mining Profitability Guide'),
('Bitcoin Adoption Trends'),
('Crypto Market Cycles'),
('Layer 1 vs Layer 2'),
('Understanding Smart Contracts'),
('Meme Coin Investing Risks'),
('Wallet Security Checklist'),
('Crypto Investing Mistakes'),
('Future of Digital Assets');
