#!/usr/bin/env python3
"""
stitch-inject.py — Inject each StitchBlogs entry into 2 relevant existing blog pages.

Reads tmp-stitch-slugs.json (generated by stitch-slugs.py) and injects a link card
into 2 relevant target pages per blog post.

Injection method:
  - "Related Articles" aside (append link card before closing </div></aside>)
  - Or body card section (append after last is-X card in two-letter-words.astro)

Target mapping:
  - is-X-a-scrabble-word posts → two-letter-words.astro + relevant letter-specific page
  - words-with-prefix-X posts → common-bingo-prefixes.astro + bingo-stem-strategy.astro
"""

import os
import re
import json
import sys

BLOG_DIR = os.path.join(
    os.path.dirname(os.path.abspath(__file__)),
    "..", "src", "pages", "blog"
)

INPUT_FILE = os.path.join(
    os.path.dirname(os.path.abspath(__file__)),
    "..", "tmp-stitch-slugs.json"
)

# --- Target mapping ---
# For "is-X" posts: which letter determines the target page
# LI, NA, NU, PO, SH, TI are all two-letter words
IS_WORD_TARGETS = {
    "is-li-a-scrabble-word": {
        "letter": "l",
        "targets": ["two-letter-words.astro", "most-useful-two-letter-words.astro"],
    },
    "is-na-a-scrabble-word": {
        "letter": "n",
        "targets": ["two-letter-words.astro", "rare-two-letter-scrabble-words.astro"],
    },
    "is-nu-a-scrabble-word": {
        "letter": "n",
        "targets": ["two-letter-words.astro", "most-useful-two-letter-words.astro"],
    },
    "is-po-a-scrabble-word": {
        "letter": "p",
        "targets": ["two-letter-words.astro", "rare-two-letter-scrabble-words.astro"],
    },
    "is-sh-a-scrabble-word": {
        "letter": "s",
        "targets": ["two-letter-words.astro", "rare-two-letter-scrabble-words.astro"],
    },
    "is-ti-a-scrabble-word": {
        "letter": "t",
        "targets": ["two-letter-words.astro", "most-useful-two-letter-words.astro"],
    },
}

PREFIX_TARGETS = {
    "words-with-prefix-bi": {
        "targets": ["common-bingo-prefixes.astro", "bingo-stem-strategy.astro"],
    },
    "words-with-prefix-mono": {
        "targets": ["common-bingo-prefixes.astro", "bingo-stem-strategy.astro"],
    },
    "words-with-prefix-poly": {
        "targets": ["common-bingo-prefixes.astro", "eight-letter-bingos-guide.astro"],
    },
    "words-with-prefix-tri": {
        "targets": ["common-bingo-prefixes.astro", "bingo-stem-strategy.astro"],
    },
}

# --- Templates ---

RELATED_ARTICLE_LINK = '''          <a href="/blog/{slug}/" class="flex items-center gap-3 p-3 rounded-lg border border-gray-800 hover:border-blue-700 hover:bg-blue-900/10 transition-all group">
            <span class="text-blue-500 group-hover:translate-x-0.5 transition-transform">\u2192</span>
            <span class="text-sm text-gray-300 group-hover:text-blue-400 transition-colors">{title}</span>
          </a>'''

BODY_CARD = '''
      <a href="/blog/{slug}/" class="block p-4 rounded-lg border border-gray-800 hover:border-blue-700 hover:bg-blue-900/10 transition-all group">
        <h2 class="text-lg font-semibold text-white group-hover:text-blue-400 transition-colors">{title}</h2>
        <p class="text-sm text-gray-400 mt-1">{description}</p>
      </a>'''


def inject_related_aside(filepath: str, slug: str, title: str) -> bool:
    """Inject a link into the Related Articles aside section."""
    full_path = os.path.join(BLOG_DIR, filepath)
    if not os.path.exists(full_path):
        print(f"    SKIP (not found): {filepath}")
        return False

    with open(full_path, "r", encoding="utf-8") as f:
        content = f.read()

    # Already present?
    if slug in content:
        print(f"    SKIP (already linked): {filepath}")
        return False

    # Find Related Articles aside → grid gap-3 → inject before closing </div>\n      </aside>
    pattern = r'(<!-- Related Articles -->.*?<div class="grid gap-3">)(.*?)(</div>\s*</aside>)'
    match = re.search(pattern, content, re.DOTALL)

    if match:
        link_html = RELATED_ARTICLE_LINK.format(slug=slug, title=title)
        new_content = content[:match.end(2)] + "\n" + link_html + content[match.end(2):]
        with open(full_path, "w", encoding="utf-8") as f:
            f.write(new_content)
        print(f"    INJECTED (Related Articles aside): {filepath}")
        return True

    # Fallback: try to find any aside with "Related" heading
    pattern2 = r'(<aside[^>]*>.*?<div class="grid gap-3">)(.*?)(</div>\s*</aside>)'
    match2 = re.search(pattern2, content, re.DOTALL)
    if match2:
        link_html = RELATED_ARTICLE_LINK.format(slug=slug, title=title)
        new_content = content[:match2.end(2)] + "\n" + link_html + content[match2.end(2):]
        with open(full_path, "w", encoding="utf-8") as f:
            f.write(new_content)
        print(f"    INJECTED (aside fallback): {filepath}")
        return True

    print(f"    SKIP (no aside section found): {filepath}")
    return False


def inject_body_card(filepath: str, slug: str, title: str, description: str) -> bool:
    """Inject a body card (for is-X posts into two-letter-words.astro landing)."""
    full_path = os.path.join(BLOG_DIR, filepath)
    if not os.path.exists(full_path):
        print(f"    SKIP (not found): {filepath}")
        return False

    with open(full_path, "r", encoding="utf-8") as f:
        content = f.read()

    if slug in content:
        print(f"    SKIP (already has card): {filepath}")
        return False

    # Find the last is-*-a-scrabble-word card and insert after
    last_end = -1
    for m in re.finditer(r'<a href="/blog/is-\w+-a-scrabble-word/"[^>]*>.*?</a>', content, re.DOTALL):
        last_end = m.end()

    if last_end == -1:
        # No existing is-X cards — try injecting into Related Articles instead
        print(f"    SKIP (no is-X cards found, trying aside): {filepath}")
        return inject_related_aside(filepath, slug, title)

    card_html = BODY_CARD.format(slug=slug, title=title, description=description)
    new_content = content[:last_end] + card_html + content[last_end:]

    with open(full_path, "w", encoding="utf-8") as f:
        f.write(new_content)

    print(f"    INJECTED (body card): {filepath}")
    return True


def main():
    if not os.path.exists(INPUT_FILE):
        print(f"ERROR: {INPUT_FILE} not found. Run stitch-slugs.py first.", file=sys.stderr)
        return 1

    with open(INPUT_FILE, "r", encoding="utf-8") as f:
        slugs_data = json.load(f)

    print("=" * 60)
    print("Blog Link Injection Script (StitchBlogs)")
    print("=" * 60)

    results = []  # Track: {slug, target_page, method, success}

    for entry in slugs_data:
        slug = entry["slug"]
        title = entry["title"]
        description = entry["description"]

        print(f"\n--- {slug} ---")

        # Determine targets
        if slug in IS_WORD_TARGETS:
            config = IS_WORD_TARGETS[slug]
            targets = config["targets"]
            # First target: body card into two-letter-words.astro
            success = inject_body_card(targets[0], slug, title, description)
            results.append({"slug": slug, "target": targets[0], "method": "body_card", "success": success})
            # Second target: related aside
            success = inject_related_aside(targets[1], slug, title)
            results.append({"slug": slug, "target": targets[1], "method": "related_aside", "success": success})

        elif slug in PREFIX_TARGETS:
            config = PREFIX_TARGETS[slug]
            targets = config["targets"]
            for target in targets:
                success = inject_related_aside(target, slug, title)
                results.append({"slug": slug, "target": target, "method": "related_aside", "success": success})

        else:
            print(f"    WARNING: No target mapping for {slug}")
            results.append({"slug": slug, "target": "NONE", "method": "none", "success": False})

    # Summary
    print("\n" + "=" * 60)
    print("INJECTION REPORT")
    print("=" * 60)
    print(f"\n{'Blog Slug':<35} {'Target Page':<40} {'Method':<15} {'Result'}")
    print("-" * 110)

    modified_files = set()
    for r in results:
        status = "✅" if r["success"] else "⏭️ skip"
        print(f"{r['slug']:<35} {r['target']:<40} {r['method']:<15} {status}")
        if r["success"]:
            modified_files.add(r["target"])

    print(f"\nTotal injections: {sum(1 for r in results if r['success'])} successful")
    print(f"Files modified: {len(modified_files)}")
    for f in sorted(modified_files):
        print(f"  src/pages/blog/{f}")

    # Write results JSON for audit
    results_file = os.path.join(os.path.dirname(os.path.abspath(__file__)), "..", "tmp-stitch-results.json")
    with open(results_file, "w", encoding="utf-8") as f:
        json.dump(results, f, indent=2)
    print(f"\nResults saved to: {results_file}")

    return 0


if __name__ == "__main__":
    sys.exit(main())
