CREATE TABLE IF NOT EXISTS tools (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  name TEXT NOT NULL,
  description TEXT NOT NULL DEFAULT '',
  category TEXT NOT NULL DEFAULT '',
  rating REAL NOT NULL DEFAULT 0,
  pricing TEXT DEFAULT '',
  url TEXT DEFAULT '',
  badge TEXT DEFAULT '',
  status INTEGER NOT NULL DEFAULT 1,
  sort_order INTEGER NOT NULL DEFAULT 0,
  created_at TEXT NOT NULL DEFAULT (datetime('now')),
  updated_at TEXT NOT NULL DEFAULT (datetime('now'))
);

INSERT INTO tools (name, description, category, rating, pricing, url, badge, sort_order) VALUES
('Cloudflare Workers AI', 'Edge-deployed LLM inference with Llama, Kimi, and embedding models. Zero cold starts, global distribution.', 'AI & LLMs', 4.8, 'Free tier', 'https://developers.cloudflare.com/workers-ai/', 'We use this', 1),
('OpenAI / ChatGPT', 'Industry-leading language models for content generation, analysis, and conversational AI applications.', 'AI & LLMs', 4.7, 'From $20/mo', 'https://openai.com/', '', 2),
('Anthropic Claude', 'Safe, high-context AI assistant with strong reasoning and coding capabilities.', 'AI & LLMs', 4.6, 'From $20/mo', 'https://claude.ai/', '', 3),
('Google Gemini', 'Multimodal AI model for text, image, audio and video generation and understanding.', 'AI & LLMs', 4.5, 'Freemium', 'https://gemini.google.com/', '', 4),
('Cloudflare Workers', 'Serverless edge computing platform. Deploy globally in seconds with sub-100ms response times.', 'Infrastructure', 4.9, 'Free tier', 'https://workers.cloudflare.com/', 'We use this', 5),
('Astro', 'Content-driven web framework. Pre-renders for speed, SSR for dynamic content. Perfect for SEO.', 'Infrastructure', 4.8, 'Free', 'https://astro.build/', 'We use this', 6),
('Cloudflare D1', 'Serverless SQLite database at the edge. Full SQL with 5ms reads and automatic replication.', 'Infrastructure', 4.7, 'Free tier', 'https://developers.cloudflare.com/d1/', 'We use this', 7),
('Cloudflare Vectorize', 'Vector database for RAG and semantic search. Powers our AI chatbot knowledge retrieval.', 'Infrastructure', 4.6, 'Included', 'https://developers.cloudflare.com/vectorize/', 'We use this', 8),
('Tailwind CSS', 'Utility-first CSS framework for rapid, consistent UI development. No custom CSS needed.', 'Design & Content', 4.8, 'Free', 'https://tailwindcss.com/', 'We use this', 9),
('Canva', 'Design platform for creating social media graphics, presentations, and marketing materials with AI tools.', 'Design & Content', 4.8, 'Freemium', 'https://www.canva.com/', '', 10),
('Jasper AI', 'AI-powered platform for generating marketing copy, blog posts, and branded content at scale.', 'Design & Content', 4.8, 'From $49/mo', 'https://www.jasper.ai/', '', 11),
('Notion', 'All-in-one workspace for notes, documentation, project management and databases with AI features.', 'Productivity', 4.7, 'Freemium', 'https://www.notion.so/', '', 12),
('Slack', 'Team communication platform with channels, messaging, integrations, and AI-powered search.', 'Productivity', 4.5, 'From $8.75/mo', 'https://slack.com/', '', 13),
('Calendly', 'Scheduling automation that simplifies booking meetings. Integrates with Google Meet and calendars.', 'Productivity', 4.7, 'Freemium', 'https://calendly.com/', 'We use this', 14),
('GitHub', 'Code hosting, version control, and collaboration platform. The backbone of modern development.', 'Productivity', 4.8, 'Freemium', 'https://github.com/', 'We use this', 15),
('Google Search Console', 'Monitor search performance, index status, and crawl health. Essential for SEO tracking.', 'Marketing & Analytics', 4.6, 'Free', 'https://search.google.com/search-console/', 'We use this', 16),
('Mailchimp', 'Email marketing platform with automation, segmentation, and analytics. Generous free plan.', 'Marketing & Analytics', 4.4, 'Freemium', 'https://mailchimp.com/', '', 17),
('HubSpot', 'All-in-one inbound marketing platform with email, SEO, social media, and CRM automation.', 'Marketing & Analytics', 4.5, 'Freemium', 'https://www.hubspot.com/', '', 18),
('Playwright', 'End-to-end browser testing framework. Reliable cross-browser testing with auto-wait and assertions.', 'Testing & Security', 4.8, 'Free', 'https://playwright.dev/', 'We use this', 19),
('Aikido Security', 'SAST scanning, secrets detection, and vulnerability analysis integrated into CI/CD pipelines.', 'Testing & Security', 4.5, 'Freemium', 'https://www.aikido.dev/', 'We use this', 20),
('Intercom', 'Customer messaging platform with live chat, chatbots, and targeted messaging for support and sales.', 'Customer Support', 4.5, 'From $29/mo', 'https://www.intercom.com/', '', 21),
('Freshdesk', 'Omnichannel help desk with AI chatbot, automation, and self-service for growing businesses.', 'Customer Support', 4.4, 'Freemium', 'https://www.freshdesk.com/', '', 22),
('Tidio', 'Live chat and chatbot platform with AI responses and omnichannel support for small businesses.', 'Customer Support', 4.7, 'Freemium', 'https://www.tidio.com/', '', 23),
('Zapier', 'No-code automation connecting thousands of apps with multi-step workflows and AI features.', 'Automation', 4.5, 'Freemium', 'https://zapier.com/', '', 24),
('Kiro', 'AI-powered development environment. Our primary coding partner for building and maintaining platforms.', 'Automation', 4.9, 'Subscription', 'https://kiro.dev/', 'We use this', 25);
