-- Seed blog ideas
INSERT INTO blog_ideas (category, title) VALUES
-- Beginner Guides
('Beginner Guides', 'What Is Scrabble?'),
('Beginner Guides', 'How to Play Scrabble'),
('Beginner Guides', 'Scrabble Rules Explained'),
('Beginner Guides', 'Scrabble Scoring Guide'),
('Beginner Guides', 'Understanding Premium Squares'),
('Beginner Guides', 'How Blank Tiles Work'),
('Beginner Guides', 'Beginner Scrabble Strategy'),
('Beginner Guides', 'Common Mistakes New Players Make'),
('Beginner Guides', 'How to Win More Scrabble Games'),
('Beginner Guides', 'Scrabble Etiquette'),
-- Two-Letter Words
('Two-Letter Words', 'Complete List of Two-Letter Scrabble Words'),
('Two-Letter Words', 'Best Two-Letter Words in Scrabble'),
('Two-Letter Words', 'Two-Letter Words With Q'),
('Two-Letter Words', 'Two-Letter Words With X'),
('Two-Letter Words', 'Two-Letter Words With Z'),
('Two-Letter Words', 'Most Useful Two-Letter Words'),
('Two-Letter Words', 'Memorizing Two-Letter Words'),
('Two-Letter Words', 'Rare Two-Letter Scrabble Words'),
('Two-Letter Words', 'Two-Letter Words by Alphabet'),
('Two-Letter Words', 'Printable Two-Letter Word List'),
-- Three-Letter Words
('Three-Letter Words', 'Best Three-Letter Scrabble Words'),
('Three-Letter Words', 'Common Three-Letter Words'),
('Three-Letter Words', 'Highest Scoring Three-Letter Words'),
('Three-Letter Words', 'Three-Letter Words With Q'),
('Three-Letter Words', 'Three-Letter Words With Z'),
('Three-Letter Words', 'Easy Three-Letter Words to Learn'),
('Three-Letter Words', 'Three-Letter Word Strategy'),
('Three-Letter Words', 'Printable Three-Letter List'),
('Three-Letter Words', 'Most Overlooked Three-Letter Words'),
('Three-Letter Words', 'Three-Letter Words for Beginners'),
-- Letter-Specific Guides
('Letter-Specific Guides', 'Words Starting With A'),
('Letter-Specific Guides', 'Words Starting With B'),
('Letter-Specific Guides', 'Words Starting With C'),
('Letter-Specific Guides', 'Words Starting With D'),
('Letter-Specific Guides', 'Words Starting With E'),
('Letter-Specific Guides', 'Words Starting With F'),
('Letter-Specific Guides', 'Words Starting With G'),
('Letter-Specific Guides', 'Words Starting With H'),
('Letter-Specific Guides', 'Words Starting With I'),
('Letter-Specific Guides', 'Words Starting With J'),
('Letter-Specific Guides', 'Words Starting With K'),
('Letter-Specific Guides', 'Words Starting With L'),
('Letter-Specific Guides', 'Words Starting With M'),
('Letter-Specific Guides', 'Words Starting With N'),
('Letter-Specific Guides', 'Words Starting With O'),
('Letter-Specific Guides', 'Words Starting With P'),
('Letter-Specific Guides', 'Words Starting With Q'),
('Letter-Specific Guides', 'Words Starting With R'),
('Letter-Specific Guides', 'Words Starting With S'),
('Letter-Specific Guides', 'Words Starting With T'),
-- More Letter Guides
('More Letter Guides', 'Words Starting With U'),
('More Letter Guides', 'Words Starting With V'),
('More Letter Guides', 'Words Starting With W'),
('More Letter Guides', 'Words Starting With X'),
('More Letter Guides', 'Words Starting With Y'),
('More Letter Guides', 'Words Starting With Z'),
('More Letter Guides', 'Words Ending With A'),
('More Letter Guides', 'Words Ending With E'),
('More Letter Guides', 'Words Ending With I'),
('More Letter Guides', 'Words Ending With O'),
('More Letter Guides', 'Words Ending With U'),
('More Letter Guides', 'Words Ending With X'),
('More Letter Guides', 'Words Ending With Z'),
('More Letter Guides', 'Words Containing Q'),
('More Letter Guides', 'Words Containing X'),
('More Letter Guides', 'Words Containing J'),
('More Letter Guides', 'Words Containing Z'),
('More Letter Guides', 'Words Containing V'),
('More Letter Guides', 'Words Containing K'),
('More Letter Guides', 'Words Containing W'),
-- High-Scoring Words
('High-Scoring Words', 'Highest Scoring Scrabble Words Ever'),
('High-Scoring Words', 'Best Q Words'),
('High-Scoring Words', 'Best Z Words'),
('High-Scoring Words', 'Best X Words'),
('High-Scoring Words', 'Best J Words'),
('High-Scoring Words', 'High Scoring Short Words'),
('High-Scoring Words', 'Highest Scoring Five-Letter Words'),
('High-Scoring Words', 'Highest Scoring Six-Letter Words'),
('High-Scoring Words', 'Highest Scoring Seven-Letter Words'),
('High-Scoring Words', 'Highest Scoring Bingos'),
-- Strategy
('Strategy', 'Rack Management Basics'),
('Strategy', 'Rack Leave Explained'),
('Strategy', 'Defensive Scrabble Strategy'),
('Strategy', 'Offensive Scrabble Strategy'),
('Strategy', 'Tile Tracking Guide'),
('Strategy', 'Endgame Strategy'),
('Strategy', 'Midgame Strategy'),
('Strategy', 'Opening Moves Guide'),
('Strategy', 'Blocking Triple Word Squares'),
('Strategy', 'Creating Parallel Plays'),
('Strategy', 'Hooking Existing Words'),
('Strategy', 'Using the S Effectively'),
('Strategy', 'When to Exchange Tiles'),
('Strategy', 'Maximizing Blank Tiles'),
('Strategy', 'Probability-Based Play'),
('Strategy', 'Position vs Points'),
('Strategy', 'Expert Scrabble Tactics'),
('Strategy', 'Common Strategic Errors'),
('Strategy', 'Risk Management in Scrabble'),
('Strategy', 'Tournament-Level Strategy'),
-- Bingo Topics
('Bingo Topics', 'What Is a Bingo?'),
('Bingo Topics', 'Best Bingo Racks'),
('Bingo Topics', 'How to Spot Bingos Faster'),
('Bingo Topics', 'Common Bingo Endings'),
('Bingo Topics', 'Common Bingo Prefixes'),
('Bingo Topics', 'Bingo Probability'),
('Bingo Topics', 'Seven-Letter Bingo List'),
('Bingo Topics', 'Eight-Letter Bingos'),
('Bingo Topics', 'Bingo Training Methods'),
('Bingo Topics', 'Famous Tournament Bingos'),
-- Statistics
('Statistics', 'Letter Frequency in Scrabble'),
('Statistics', 'Most Valuable Tile'),
('Statistics', 'Least Valuable Tile'),
('Statistics', 'Average Winning Score'),
('Statistics', 'Tile Distribution Explained'),
('Statistics', 'Probability of Drawing Q'),
('Statistics', 'Probability of Drawing Blank Tiles'),
('Statistics', 'Average Game Length'),
('Statistics', 'Highest Tournament Scores'),
('Statistics', 'Scrabble by the Numbers'),
-- Dictionary Topics
('Dictionary Topics', 'TWL vs SOWPODS'),
('Dictionary Topics', 'Official Scrabble Dictionary Guide'),
('Dictionary Topics', 'Newly Added Scrabble Words'),
('Dictionary Topics', 'Controversial Scrabble Words'),
('Dictionary Topics', 'Words Removed From Scrabble'),
('Dictionary Topics', 'Foreign-Origin Words in Scrabble'),
('Dictionary Topics', 'Slang Words Allowed in Scrabble'),
('Dictionary Topics', 'Obscure Legal Words'),
('Dictionary Topics', 'Most Surprising Valid Words'),
('Dictionary Topics', 'Invalid Words People Think Are Valid'),
-- Word Lists
('Word Lists', 'Words Without Vowels'),
('Word Lists', 'Words With Only Vowels'),
('Word Lists', 'Q Words Without U'),
('Word Lists', 'Palindrome Words'),
('Word Lists', 'Words With Double Letters'),
('Word Lists', 'Words With Triple Letters'),
('Word Lists', 'Longest Scrabble Words'),
('Word Lists', 'Shortest Legal Words'),
('Word Lists', 'Animal Names in Scrabble'),
('Word Lists', 'Food Words in Scrabble'),
('Word Lists', 'Geography Words in Scrabble'),
('Word Lists', 'Science Words in Scrabble'),
('Word Lists', 'Sports Words in Scrabble'),
('Word Lists', 'Technology Words in Scrabble'),
('Word Lists', 'Musical Terms in Scrabble'),
('Word Lists', 'Nature Words in Scrabble'),
('Word Lists', 'Medical Terms in Scrabble'),
('Word Lists', 'Historical Terms in Scrabble'),
('Word Lists', 'Four-Letter Power Words'),
('Word Lists', 'Five-Letter Power Words'),
-- Tournament & Competitive Play
('Tournament & Competitive Play', 'How Scrabble Tournaments Work'),
('Tournament & Competitive Play', 'Becoming a Tournament Player'),
('Tournament & Competitive Play', 'World Scrabble Championships'),
('Tournament & Competitive Play', 'Greatest Scrabble Players'),
('Tournament & Competitive Play', 'Tournament Rules Explained'),
('Tournament & Competitive Play', 'Time Management in Tournaments'),
('Tournament & Competitive Play', 'Scrabble Ratings Explained'),
('Tournament & Competitive Play', 'Online vs Tournament Scrabble'),
('Tournament & Competitive Play', 'Preparing for Competition'),
('Tournament & Competitive Play', 'Famous Scrabble Matches'),
-- Online Scrabble
('Online Scrabble', 'Best Scrabble Apps'),
('Online Scrabble', 'Best Online Scrabble Sites'),
('Online Scrabble', 'Scrabble vs Words With Friends'),
('Online Scrabble', 'Playing Scrabble on Mobile'),
('Online Scrabble', 'Online Scrabble Etiquette'),
('Online Scrabble', 'Multiplayer Scrabble Tips'),
('Online Scrabble', 'AI Scrabble Opponents'),
('Online Scrabble', 'Best Scrabble Training Tools'),
('Online Scrabble', 'Online Scrabble Communities'),
('Online Scrabble', 'Tracking Your Improvement'),
-- Fun & Trivia
('Fun & Trivia', 'History of Scrabble'),
('Fun & Trivia', 'Who Invented Scrabble?'),
('Fun & Trivia', 'Weird Scrabble Facts'),
('Fun & Trivia', 'Scrabble Around the World'),
('Fun & Trivia', 'Most Unusual Tournament Stories'),
('Fun & Trivia', 'Record-Breaking Scrabble Games'),
('Fun & Trivia', 'Scrabble in Different Languages'),
('Fun & Trivia', 'Scrabble and Mathematics'),
('Fun & Trivia', 'Scrabble and Memory Training'),
('Fun & Trivia', 'Scrabble and Vocabulary Growth'),
-- Educational Topics
('Educational Topics', 'Teaching Kids Scrabble'),
('Educational Topics', 'Scrabble for Language Learners'),
('Educational Topics', 'Improving Vocabulary With Scrabble'),
('Educational Topics', 'Classroom Scrabble Activities'),
('Educational Topics', 'Family Scrabble Night Ideas'),
('Educational Topics', 'Scrabble for Seniors'),
('Educational Topics', 'Cognitive Benefits of Scrabble'),
('Educational Topics', 'Scrabble and Brain Health'),
('Educational Topics', 'Learning English Through Scrabble'),
('Educational Topics', 'Scrabble Study Plans'),
-- Solver-Related Topics
('Solver-Related Topics', 'How Scrabble Solvers Work'),
('Solver-Related Topics', 'Best Scrabble Solver Tools'),
('Solver-Related Topics', 'Are Scrabble Solvers Fair?'),
('Solver-Related Topics', 'Using Wildcards in Solvers'),
('Solver-Related Topics', 'Anagram Solvers Explained'),
('Solver-Related Topics', 'Pattern Search Tools'),
('Solver-Related Topics', 'Board Position Solvers'),
('Solver-Related Topics', 'Rack Leave Calculators'),
('Solver-Related Topics', 'Scrabble Probability Calculators'),
('Solver-Related Topics', 'Ultimate Scrabble Resource Guide');
